module.exports = {
  velo: { name: 'Vélo', icon: '🚲', color: '#2a5bd7',
    c: ['Bicyclette', 'Casque de vélo', 'Pédale', 'Guidon', 'Pneumatique', 'Dérailleur', 'Cyclotourisme', 'Vélo tout terrain', 'Cyclisme sur route', 'Cyclisme sur piste', 'Vélo de course', 'BMX', 'Tricycle', 'Monocycle', 'Vélo couché', 'Vélo pliant', 'Draisienne', 'Grand bi', 'Vélocipède', 'Frein à disque', 'Roue libre', 'Cadre de bicyclette', 'Fourche (cycle)', 'Jante', 'Moyeu', 'Chambre à air', 'Selle de bicyclette', 'Cyclisme', 'Cyclo-cross', 'Vélodrome', 'Maillot jaune', 'Maillot vert', 'Maillot à pois', 'Peloton (cyclisme)', 'Échappée (cyclisme)', 'Sprint (cyclisme)', 'Contre-la-montre', 'Bicross', 'Vélo cargo', 'Cyclisme en montagne', 'Éclairage de bicyclette', 'Sonnette', 'Porte-bagages', 'Garde-boue', 'Antivol', 'Pompe à vélo', 'Vélo de ville', 'Vélo de randonnée', 'Cycliste', 'Cyclosportive'],
    r: ['Tour de France', 'Paris-Roubaix', "Tour d'Italie", "Tour d'Espagne", 'Piste cyclable', 'Vélo à assistance électrique', 'Critérium du Dauphiné', 'Tour de France féminin', 'Milan-San Remo', 'Tour des Flandres', 'Liège-Bastogne-Liège', 'Tour de Lombardie', 'Paris-Nice', 'Tour de Suisse', 'Championnats du monde de cyclisme sur route', "Alpe d'Huez", 'Col du Tourmalet', 'Mont Ventoux', 'Col du Galibier', "Vélodrome d'Hiver", "Record de l'heure", 'Cyclisme aux Jeux olympiques', "Vélib'", 'Paris-Brest-Paris', 'Maillot arc-en-ciel', 'Flèche wallonne', 'Amstel Gold Race', 'Gand-Wevelgem', 'Tour de Romandie', 'Grand Tour'],
    e: ['Bernard Hinault', 'Fausto Coppi', 'Tadej Pogačar', 'Marianne Vos', 'Lance Armstrong', 'Bernard Thévenet', 'Laurent Fignon', 'Greg LeMond', 'Chris Froome', 'Jonas Vingegaard', 'Mark Cavendish', 'Julian Alaphilippe', 'Peter Sagan', 'Raymond Poulidor'],
    l: ['Eddy Merckx', 'Jacques Anquetil', 'Miguel Induráin', 'Louison Bobet', 'Gino Bartali', 'Felice Gimondi'] },
  foot: { name: 'Football', icon: '⚽', color: '#2ea043',
    c: ['Football', 'Penalty (football)', 'Corner (football)', 'Carton jaune', 'Stade de France', 'Hors-jeu (football)', 'Coup franc', 'Gardien de but (football)', 'Ligue 1', 'Premier League', 'Ballon de football', 'Terrain de football', 'But (football)', 'Arbitre (football)', 'Carton rouge', 'Touche (football)', 'Séance de tirs au but', 'Prolongation', 'Défenseur (football)', 'Milieu de terrain', 'Attaquant (football)', 'Entraîneur de football', 'Chaussure de football', 'Maillot de football', 'Supporter', 'Stade', 'Championnat de France de football', 'Coupe de France de football', 'Ligue 2', 'Bundesliga', 'Serie A', "Championnat d'Espagne de football", 'Ligue Europa', 'Match de football', 'Dribble', 'Tacle (football)', 'Football féminin', 'Futsal', 'Beach soccer', 'Mi-temps', 'Fair-play', 'Arbitrage vidéo', "Ballon d'or", 'Football en salle', 'Transfert (football)', 'Capitaine (sport)', 'Défense en zone', 'Tir (football)', 'Passe (football)', 'Joueur de football'],
    r: ['Coupe du monde de football', "Ligue des champions de l'UEFA", 'Paris Saint-Germain Football Club', 'Olympique de Marseille', 'Real Madrid Club de Fútbol', 'Futbol Club Barcelona', 'Juventus Football Club', 'Olympique lyonnais', 'Association sportive de Saint-Étienne', 'Football Club de Nantes', 'Girondins de Bordeaux', 'Manchester United Football Club', 'Liverpool Football Club', 'Arsenal Football Club', 'Chelsea Football Club', 'Football Club Bayern Munich', 'Borussia Dortmund', 'Associazione Calcio Milan', 'Football Club Internazionale Milano', 'Ajax Amsterdam', "Championnat d'Europe de football", 'Coupe du monde de football de 1998', 'Camp Nou', 'Stade Santiago-Bernabéu', 'Old Trafford', 'Stade de Wembley', 'Parc des Princes', 'Stade Vélodrome', 'Maracanã', 'Équipe de France de football'],
    e: ['Zinédine Zidane', 'Kylian Mbappé', 'Michel Platini', 'Thierry Henry', 'Cristiano Ronaldo', 'Neymar', 'Karim Benzema', 'Antoine Griezmann', 'Just Fontaine', 'Éric Cantona', 'Franz Beckenbauer', 'Johan Cruyff', 'Ronaldo (football, 1976)', 'Zlatan Ibrahimović'],
    l: ['Pelé', 'Diego Maradona', 'Lionel Messi', 'Ferenc Puskás', 'Alfredo Di Stéfano', 'Garrincha'] },
  espace: { name: 'Espace', icon: '🚀', color: '#7c3aed',
    c: ['Lune', 'Soleil', 'Terre', 'Mars (planète)', 'Vénus (planète)', 'Mercure (planète)', 'Comète', 'Astéroïde', 'Étoile', 'Satellite artificiel', 'Ciel', 'Galaxie', 'Constellation', 'Planète', 'Système solaire', 'Orbite', 'Atmosphère terrestre', 'Gravité', 'Éclipse solaire', 'Éclipse lunaire', 'Aurore polaire', 'Étoile filante', 'Météorite', "Ceinture d'astéroïdes", 'Fusée', 'Astronaute', 'Satellite naturel', 'Télescope', 'Observatoire astronomique', 'Planétarium', 'Nébuleuse', 'Supernova', 'Naine blanche', 'Géante rouge', 'Étoile polaire', 'Grande Ourse', 'Orion (constellation)', 'Croix du Sud', 'Phases de la Lune', 'Marée', 'Saison', 'Solstice', 'Équinoxe', 'Année-lumière', 'Vent solaire', 'Tache solaire', "Cratère d'impact", 'Météore', 'Cosmonaute', 'Agence spatiale européenne'],
    r: ['Jupiter (planète)', 'Saturne (planète)', 'Uranus (planète)', 'Neptune (planète)', 'Station spatiale internationale', 'Voie lactée', 'Pluton (planète naine)', "Galaxie d'Andromède", 'Sirius', 'Alpha du Centaure', 'Bételgeuse', 'Proxima du Centaure', 'Ganymède (lune)', 'Titan (lune)', 'Europe (lune)', 'Io (lune)', 'Encelade', 'Phobos (lune)', 'Cérès (planète naine)', 'Éris (planète naine)', 'Anneaux de Saturne', 'Grande Tache rouge', 'Olympus Mons', 'National Aeronautics and Space Administration', 'Ariane (famille de lanceurs)', 'Falcon 9', 'Mir (station spatiale)', 'Spoutnik 1', 'Programme Apollo', 'Soyouz (véhicule spatial)'],
    e: ['Apollo 11', 'Télescope spatial Hubble', 'Voyager 1', 'Trou noir', 'Télescope spatial James-Webb', 'Cassini-Huygens', 'Voyager 2', 'New Horizons', 'Laïka', 'Thomas Pesquet', 'Buzz Aldrin', 'Valentina Terechkova', 'Rosetta (sonde spatiale)', 'Sagittarius A*'],
    l: ['Iouri Gagarine', 'Neil Armstrong', 'Big Bang', 'Stephen Hawking', 'Albert Einstein', 'Sergueï Korolev'] },
  animaux: { name: 'Animaux', icon: '🦁', color: '#d97706',
    c: ['Chat', 'Chien', 'Cheval', 'Poule', 'Lapin', 'Mouton', 'Canard', 'Cochon', 'Âne', 'Vache', 'Oie', 'Dinde', 'Chèvre', 'Pigeon', 'Moineau domestique', 'Souris', 'Hamster', 'Cobaye', 'Poisson rouge', 'Perruche', 'Grenouille', 'Escargot', 'Abeille', 'Fourmi', 'Papillon', 'Coccinelle', 'Araignée', 'Hérisson', 'Écureuil roux', 'Renard roux', 'Cerf élaphe', 'Sanglier', "Lièvre d'Europe", 'Merle noir', 'Rouge-gorge familier', 'Hirondelle rustique', 'Cigogne blanche', 'Cygne tuberculé', 'Tortue', 'Mésange charbonnière', 'Chauve-souris', 'Taupe', 'Lézard des murailles', 'Couleuvre', 'Coq', 'Chat domestique', 'Ver de terre', 'Mouche', 'Moustique', 'Salamandre tachetée'],
    r: ['Lion', 'Éléphant', 'Girafe', 'Dauphin', 'Loup gris', 'Ours brun', 'Panda géant', 'Zèbre', 'Hippopotame', 'Rhinocéros', 'Guépard', 'Léopard', 'Chimpanzé', 'Kangourou', 'Koala', 'Manchot empereur', 'Ours polaire', 'Crocodile du Nil', 'Requin-baleine', 'Orque', 'Loutre', 'Flamant rose', 'Paresseux', 'Dromadaire', 'Lama', 'Hyène tachetée', 'Suricate', 'Renne', 'Phoque', 'Perroquet'],
    e: ['Tigre', 'Grand requin blanc', 'Aigle royal', 'Gorille', 'Panthère des neiges', 'Okapi', 'Ornithorynque', 'Pangolin', 'Axolotl', 'Kakapo', 'Diable de Tasmanie', 'Aye-aye', 'Narval', 'Fossa'],
    l: ['Baleine bleue', 'Dodo', 'Tyrannosaurus rex', 'Mammouth laineux', 'Smilodon', 'Mégalodon'] },
  histoire: { name: 'Histoire', icon: '🏛️', color: '#b91c1c',
    c: ['Rome antique', 'Égypte antique', 'Grèce antique', 'Moyen Âge', 'Château fort', 'Révolution française', 'Renaissance', 'Vikings', 'Gaulois', 'Préhistoire', 'Antiquité', 'Empire romain', 'Gladiateur', 'Colisée', 'Pyramide de Khéops', 'Grand Sphinx de Gizeh', 'Parthénon', 'Jeux olympiques antiques', 'Chevalier', 'Croisades', 'Guerre de Cent Ans', 'Cathédrale Notre-Dame de Paris', 'Château de Versailles', 'Prise de la Bastille', 'Siècle des Lumières', 'Peste noire', 'Féodalité', 'Grotte de Lascaux', 'Néolithique', 'Âge du bronze', 'Âge du fer', 'Mésopotamie', 'Empire byzantin', 'Empire ottoman', 'Chine antique', 'Grande Muraille de Chine', 'Guerre de Troie', 'Guerre de Sécession', 'Révolution industrielle', 'Première Guerre mondiale', 'Seconde Guerre mondiale', 'Mur de Berlin', 'Aztèques', 'Incas', 'Civilisation maya', 'Pompéi', 'Samouraï', 'Pirate', 'Hiéroglyphe', 'Pharaon'],
    r: ["Jeanne d'Arc", 'Louis XIV', 'Cléopâtre VII', 'Jules César', 'Charlemagne', 'Napoléon Ier', 'Christophe Colomb', 'Vercingétorix', 'Auguste', 'Néron', 'Hannibal Barca', 'Périclès', 'Socrate', 'Platon', 'Aristote', 'Cyrus II', 'Saladin', 'Gengis Khan', 'Richard Cœur de Lion', 'Louis IX', 'Henri IV', 'Catherine de Médicis', 'Marie-Antoinette', 'Maximilien de Robespierre', 'Louis XVI', 'Simón Bolívar', 'Abraham Lincoln', 'George Washington', 'Élisabeth Ire', 'Marco Polo'],
    e: ['Léonard de Vinci', 'Alexandre le Grand', 'Marie Curie', 'Galilée (savant)', 'Johannes Gutenberg', 'Nicolas Copernic', 'Isaac Newton', 'Charles de Gaulle', 'Winston Churchill', 'Nelson Mandela', 'Mahatma Gandhi', 'Mansa Moussa', 'Néfertiti', 'Qin Shi Huang'],
    l: ['Ramsès II', 'Attila', 'Toutânkhamon', 'Soliman le Magnifique', 'Hatchepsout', 'Akhénaton'] },
  hand: { name: 'Handball', icon: '🤾', color: '#0891b2',
    c: ['Handball', 'Ballon de handball', 'Terrain de handball', 'But (handball)', 'Gardien de but (handball)', 'Ailier (handball)', 'Pivot (handball)', 'Arrière (handball)', 'Demi-centre (handball)', 'Jet de sept mètres', 'Zone de but (handball)', 'Tir en suspension', 'Passe (handball)', 'Dribble (handball)', 'Arbitre (handball)', 'Carton jaune (handball)', 'Exclusion temporaire', 'Temps mort (handball)', 'Mi-temps', 'Contre-attaque', 'Défense (handball)', 'Fédération française de handball', 'Fédération internationale de handball', 'Championnat de France de handball', 'Coupe de France de handball', 'Handball féminin', 'Handball à onze', 'Beach handball', "Championnat d'Europe de handball", 'Championnat du monde de handball', 'Handball aux Jeux olympiques', 'Ligue des champions de handball', 'Sport collectif', 'Gymnase', 'Sifflet', 'Chronomètre', 'Supporter', 'Entraîneur sportif', 'Joueur de handball', 'Ballon', 'Chaussure de sport', 'Échauffement', 'Feinte', 'Sport olympique', 'Règles du handball', 'Arbitrage vidéo', 'Basket-ball', 'Volley-ball', 'Football', "Sport d'équipe"],
    r: ['Équipe de France masculine de handball', 'Équipe de France féminine de handball', 'Paris Saint-Germain Handball', 'Montpellier Handball', 'Handball Club de Nantes', 'Chambéry Savoie Mont Blanc Handball', 'Saint-Raphaël Var Handball', 'Fenix Toulouse Handball', 'Fútbol Club Barcelona (handball)', 'THW Kiel', 'SG Flensburg-Handewitt', 'Telekom Veszprém KC', 'Vive Kielce', 'Handball-Bundesliga', 'Ligue nationale de handball', 'Metz Handball', 'Brest Bretagne Handball', 'Győri ETO KC', 'CSM Bucarest (handball)', 'Équipe du Danemark masculine de handball', 'Équipe de Suède masculine de handball', "Équipe d'Espagne masculine de handball", 'Équipe de Norvège féminine de handball', 'Accor Arena', 'Ligue européenne de handball', "Handball aux Jeux olympiques d'été de 2024", 'Championnat du monde masculin de handball 2001', 'Championnat du monde masculin de handball 2015', "Championnat d'Europe masculin de handball 2024", 'Coupe de la Ligue française de handball'],
    e: ['Luka Karabatić', 'Guillaume Gille', 'Daniel Narcisse', 'Jérôme Fernandez', 'Bertrand Gille', 'Didier Dinart', 'Claude Onesta', 'Sander Sagosen', 'Ludovic Fabregas', 'Allison Pineau', 'Estelle Nze Minko', 'Cléopâtre Darleux', 'Nora Mørk', 'Nedim Remili'],
    l: ['Nikola Karabatić', 'Mikkel Hansen', 'Thierry Omeyer', 'Jackson Richardson', 'Ivano Balić', 'Talant Dujshebaev', 'Moury Nolan'] },
};

// Niveaux 2 à 5 : une collection différente par niveau (clé "foot2", "foot3"…), débloquée par les renaissances de la même ligne.
{
  const LV = require('./levels.json'), ROM = ['II', 'III', 'IV', 'V'], out = {};
  for (const [k, o] of Object.entries(module.exports)) {
    out[k] = o;
    (LV[k] || []).forEach((l, i) => { out[k + (i + 2)] = { name: o.name + ' ' + ROM[i], icon: o.icon, color: o.color, lv: i + 2, base: k, c: l[0], r: l[1], e: l[2], l: l[3] }; });
  }
  module.exports = out;
}
