module.exports = {
  velo: { name: 'Vélo', icon: '🚲', color: '#2a5bd7',
    c: ['Bicyclette', 'Casque de vélo', 'Pédale', 'Guidon', 'Pneumatique', 'Dérailleur', 'Cyclotourisme', 'Vélo tout terrain', 'Cyclisme sur route', 'Cyclisme sur piste'],
    r: ['Tour de France', 'Paris-Roubaix', "Tour d'Italie", "Tour d'Espagne", 'Piste cyclable', 'Vélo à assistance électrique', 'Critérium du Dauphiné'],
    e: ['Bernard Hinault', 'Fausto Coppi', 'Tadej Pogačar', 'Marianne Vos'],
    l: ['Eddy Merckx', 'Jacques Anquetil', 'Miguel Induráin'] },
  foot: { name: 'Football', icon: '⚽', color: '#2ea043',
    c: ['Football', 'Penalty (football)', 'Corner (football)', 'Carton jaune', 'Stade de France', 'Hors-jeu (football)', 'Coup franc', 'Gardien de but (football)', 'Ligue 1', 'Premier League'],
    r: ['Coupe du monde de football', "Ligue des champions de l'UEFA", 'Paris Saint-Germain Football Club', 'Olympique de Marseille', 'Real Madrid Club de Fútbol', 'Futbol Club Barcelona', 'Juventus Football Club'],
    e: ['Zinédine Zidane', 'Kylian Mbappé', 'Michel Platini', 'Thierry Henry'],
    l: ['Pelé', 'Diego Maradona', 'Lionel Messi'] },
  espace: { name: 'Espace', icon: '🚀', color: '#7c3aed',
    c: ['Lune', 'Soleil', 'Terre', 'Mars (planète)', 'Vénus (planète)', 'Mercure (planète)', 'Comète', 'Astéroïde', 'Étoile', 'Satellite artificiel'],
    r: ['Jupiter (planète)', 'Saturne (planète)', 'Uranus (planète)', 'Neptune (planète)', 'Station spatiale internationale', 'Voie lactée', 'Pluton (planète naine)'],
    e: ['Apollo 11', 'Télescope spatial Hubble', 'Voyager 1', 'Trou noir'],
    l: ['Iouri Gagarine', 'Neil Armstrong', 'Big Bang'] },
  animaux: { name: 'Animaux', icon: '🦁', color: '#d97706',
    c: ['Chat', 'Chien', 'Cheval', 'Poule', 'Lapin', 'Mouton', 'Canard', 'Cochon', 'Âne', 'Vache'],
    r: ['Lion', 'Éléphant', 'Girafe', 'Dauphin', 'Loup gris', 'Ours brun', 'Panda géant'],
    e: ['Tigre', 'Grand requin blanc', 'Aigle royal', 'Gorille'],
    l: ['Baleine bleue', 'Dodo', 'Tyrannosaurus rex'] },
  histoire: { name: 'Histoire', icon: '🏛️', color: '#b91c1c',
    c: ['Rome antique', 'Égypte antique', 'Grèce antique', 'Moyen Âge', 'Château fort', 'Révolution française', 'Renaissance', 'Vikings', 'Gaulois', 'Préhistoire'],
    r: ["Jeanne d'Arc", 'Louis XIV', 'Cléopâtre VII', 'Jules César', 'Charlemagne', 'Napoléon Ier', 'Christophe Colomb'],
    e: ['Léonard de Vinci', 'Alexandre le Grand', 'Marie Curie', 'Galilée (savant)'],
    l: ['Ramsès II', 'Attila', 'Toutânkhamon'] },
};
